title: Dom's Blog
subtitle: Dom's Blog

url: "https://zeropwn.github.io"
baseurl: ""

footer_url: "https://github.com/zeropwn"
footer_text: "written with love and caffeine"

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Twitter"
   link: "https://www.twitter.com/zer0pwn"
